#!/usr/bin/env ruby

def hi(name)
  puts "Hello #{name}"
  #puts $0
end

#hi(__FILE__)

def ohai(*args)
	print "\r\033[2K  [ \033[0;34m..\033[0m ] ", *args, "\n"
	print "\r\033[2K  [ \033[1;32mOK\033[0m ] ", *args, "\n"
	print "\r\033[2K  [\033[0;31mFAIL\033[0m] ", *args, "\n"
end


ohai "Install Homebrew"
