#!/usr/bin/env ruby

DOTROOT = __dir__

if __FILE__ == $0
	require "#{DOTROOT}/recipe.rb"
end

def os
	case RUBY_PLATFORM
		when /x86/
			:macos
		else
			raise "unknown os"
	end
end

def test
	if os == :macos
		print "Y"
		print RUBY_PLATFORM
	else
		print "N"
	end
end

test
